### ISSUE TITLE
Attempt to invoke virtual method on a null object reference

### ISSUE THREAD

**Issue by MLK57** [StasDoskalenko/react-native-google-fit#112]
When i want to use react-native-google-fit I have this error that is displayed every time
![error fit](https://user-images.githubusercontent.com/50232392/61292747-4ee34a00-a7d2-11e9-9ff7-92c362426155.png)

someone has a solution ??

**Comment by manacespereira** [comment]
same issue here

**Comment by Karpengold** [comment]
Same issue

**Comment by Karpengold** [comment]
I think you just tried to use package methods before authorizing — that was my problem

**Comment by manacespereira** [comment]
> I think you just tried to use package methods before authorizing — that was my problem

No. That is'nt my problem. This was solved, but I did not anything, only --reset-cache and "re-link" the library manually...

**Comment by DoThanhLoc** [comment]
same issue

**Comment by marcoautiero** [comment]
same issue here; I gave the authorizations in a welcome screen of my app, then now every time I run the app I receive this error message

**Comment by 007486215** [comment]
Same issue, I tied re-link and reset cache but still not work

**Comment by laibagill** [comment]
same issue

**Comment by Shahulul** [comment]
same issue

**Comment by chefk5** [comment]
same issue too

**Comment by ksetrin** [comment]
This issue happens when you try to get data from GoogleFit in the next launch of app
I **resolved** it with the following code
```
                 GoogleFit.checkIsAuthorized()
                    .then(() => {
                        if (!GoogleFit.isAuthorized) {
                            return this.authorize(); // at first do GoogleFit.authorize(options)
                        }
                    })
                    .then(() => {
                      ...get steps or what you want
                    }
```
So, if the user already grant permissions for Google Fit that GoogleFit.authorize don't show pop-up and return `{success: true}` immediately
