### ISSUE TITLE
error: cannot find symbol issue in GoogleSignInAccount gsa = GoogleSignIn.getAccountForScopes(mReactContext, new Scope(Scopes.FITNESS_ACTIVITY_READ))

### ISSUE THREAD

**Issue by nikhil-kumar-160** [StasDoskalenko/react-native-google-fit#268]
I started a new react native project where I have to use google fit.
after installing the package, my android build is not compiling due to this error.

![Screenshot 2021-12-10 at 2 28 46 PM](https://user-images.githubusercontent.com/89442532/145546453-0a077d32-4852-47c7-a153-94026bc14eb6.png)

`"react-native": "0.66.4",`
`"react-native-google-fit": "^0.18.1"`

@StasDoskalenko is it due to some changes in google fit sdk?

**Comment by mnakai** [comment]
I am facing the same problem.

react-native: 0.66.3
react-native-google-fit: 0.18.1
Xcode: 13.1
Java: 11.0.4

**Comment by nikhil-kumar-160** [comment]
I have found a temporary solution for this.

Just replace the line which has error with this

`GoogleSignInAccount gsa = GoogleSignIn.getAccountForScopes(mReactContext, new Scope("https://www.googleapis.com/auth/fitness.activity.read"));`


It should fix the issue.

I think the issue is related to import of the scope object from the dir: react-native-google-fit/src/scopes.js

**Comment by Satendra-SR** [comment]
I'm facing the same issue since this morning. I'm running with the following configuration
```
react-native: 0.66.3
react-native-google-fit: 0.18.1
Android Studio: Android Studio Arctic Fox | 2020.3.1 Patch 3
Java: 11.0.12
```

**Comment by nikhil-kumar-160** [comment]
@Satendra-SR , try the above solution. It can fix your issue temporarily

**Comment by Nikooos** [comment]
This error emerged here since this morning as well.

**Comment by imravivarma** [comment]
> @mnakai
> 
> I have found a temporary solution for this.
> 
> Just replace the line which has error with this go to `Project_Dir/node_modules/react-native-google-fit/android/src/main/java/com/reactnative/googlefit/GoogleFitManager.java`
> 
> on line 199, you will find the line that is causing the error. just replace it with the line below
> 
> `GoogleSignInAccount gsa = GoogleSignIn.getAccountForScopes(mReactContext, new Scope("https://www.googleapis.com/auth/fitness.activity.read"));`
> 
> It should fix the issue.
> 
> I think the issue is related to import of the scope object from the dir: react-native-google-fit/src/scopes.js

**Comment by zvs001** [comment]
Before issue is solved by library, you can setup postinstall script:
```
sed -i -e 's/Scopes.FITNESS_ACTIVITY_READ/"https:\/\/www.googleapis.com\/auth\/fitness.activity.read"/g' \
 node_modules/react-native-google-fit/android/src/main/java/com/reactnative/googlefit/GoogleFitManager.java
```

**Comment by t2tx** [comment]
It may be due to a version up of the google play service.
- https://developers.google.com/android/guides/releases?hl=en

You can modify the android/build.gradle file of the root project to avoid this error

```
buildscript {
  ext {
       ... 
       authVersion = "19.0.0"
       fitnessVersion = "20.0.0"
  }
  ...
```

**Comment by AcidNoX** [comment]
@t2tx This worked for me. Thank you - been banging my head against a brick wall with this all afternoon.

**Comment by sinn1** [comment]
@t2tx 

> It may be due to a version up of the google play service.
> 
> * https://developers.google.com/android/guides/releases?hl=en
> 
> You can modify the android/build.gradle file of the root project to avoid this error
> 
> ```
> buildscript {
>   ext {
>        ... 
>        authVersion = "19.0.0"
>        fitnessVersion = "20.0.0"
>   }
>   ...
> ```

This worked for me too. I had to set BOTH authVersion and fitnessVersion for it to work. fitnessVersion by itself was still throwing the error.

**Comment by aboveyunhai** [comment]
For anyone who wonder what happens
![image](https://user-images.githubusercontent.com/35160613/145637439-5c705fd2-d311-4e63-ac1f-a2da110ceda3.png)

This package always use up to date version of google service, so symbol is missing.

**@t2tx  is the standard approach for any who used this lib, to fix your current Apk version and keep the consistency of your app.** 

@nikhil-kumar-160  the temp solution might work but I'm not sure if it will break the logout functionalities.
If it still works, I will push it as a dirty hot fix.

The main problem is that the deprecated SignIn mechanism starts to bite us back, 
I did leave chunk of standard SignIn code (comment out) since last update, I'm not sure when I should kick them in. 
If so, there will be a big rewrite of entire codebase.

**Comment by aboveyunhai** [comment]
0.18.2 is released.

**Comment by poojapatidar28** [comment]
Slove this error please

error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
